set(CMAKE_FIND_ROOT_PATH ${CROSS_COMPILE_PATH})
set(THREADS_PTHREAD_ARG ${CROSS_COMPILE_PATH})
set(CMAKE_LIBRARY_ARCHITECTURE ${HOST})

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
